opentreemap/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division

from django.conf.urls import patterns, url

from django_tinsel.decorators import route

from api.views import (status_view, version_view, public_instances_endpoint,
                       remove_current_tree_from_plot, plots_endpoint,
                       species_list_endpoint, approve_pending_edit,
                       reject_pending_edit, update_user_endpoint,
                       reset_password_endpoint, user_endpoint,
                       plot_endpoint, edits, plots_closest_to_point_endpoint,
                       instance_info_endpoint, add_photo_endpoint,
                       export_users_csv_endpoint, export_users_json_endpoint,
                       update_profile_photo_endpoint,
                       instances_closest_to_point_endpoint)

from treemap.instance import URL_NAME_PATTERN


instance_pattern = (r'^instance/(?P<instance_url_name>' +
                    URL_NAME_PATTERN + r')')

lat_lon_pattern = '(?P<lat>-{0,1}\d+(\.\d+){0,1}),' \
                  '(?P<lng>-{0,1}\d+(\.\d+){0,1})'

urlpatterns = patterns(
    '',
    (r'^$', status_view),
    (r'^version$', version_view),

    url(r'^user$', user_endpoint, name='user_info'),
    url(r'^user/(?P<user_id>\d+)$', update_user_endpoint,
        name='update_user'),
    url(r'^user/(?P<user_id>\d+)/photo$', update_profile_photo_endpoint,
        name='update_user_photo'),
    (r'^user/(?P<user_id>\d+)/edits$', edits),

    (r'^send-password-reset-email$', reset_password_endpoint),

    ('^locations/' + lat_lon_pattern + '/instances',
     instances_closest_to_point_endpoint),

    ('^instances', public_instances_endpoint),

    (instance_pattern + r'/plots/(?P<plot_id>\d+)/tree/photo$',
     add_photo_endpoint),

    (instance_pattern + r'/plots/(?P<plot_id>\d+)/tree$',
     route(DELETE=remove_current_tree_from_plot)),

    (instance_pattern + r'/pending-edits/(?P<pending_edit_id>\d+)/approve',
     route(POST=approve_pending_edit)),

    (instance_pattern + r'/pending-edits/(?P<pending_edit_id>\d+)/reject',
     route(POST=reject_pending_edit)),

    # OTM2/instance endpoints
    (instance_pattern + '$', instance_info_endpoint),
    (instance_pattern + '/species$', species_list_endpoint),
    (instance_pattern + r'/plots$', plots_endpoint),
    (instance_pattern + r'/plots/(?P<plot_id>\d+)$',
     plot_endpoint),
    (instance_pattern + r'/locations/' + lat_lon_pattern + '/plots',
     plots_closest_to_point_endpoint),
    url(instance_pattern + r'/users.csv',
        export_users_csv_endpoint, name='user_csv'),
    url(instance_pattern + r'/users.json',
        export_users_json_endpoint, name='user_json'),
)

opentreemap/importer/urls.py
# -*- coding: utf-8 -*-
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division

from django.conf.urls import patterns, url

from importer.views import (
    start_import_endpoint, update_row_endpoint, export_all_species,
    export_single_species_import, export_single_tree_import, merge_species,
    commit_endpoint, counts, show_import_status_endpoint,
    list_imports_endpoint, refresh_imports_endpoint, solve_endpoint)

from treemap.plugin import feature_enabled

_type_pattern = '(?P<import_type>(species|tree))'
_ie_pattern = '(?P<import_event_id>\d+)'
_import_api_pattern = _type_pattern + '/' + _ie_pattern


urlpatterns = patterns(
    '',
    url(r'^$', list_imports_endpoint, name='list_imports'),
    url(r'^refresh$', refresh_imports_endpoint, name='refresh_imports'),
    url(r'^start_import$', start_import_endpoint, name='start_import'),
    url(r'^status/%s/' % _import_api_pattern, show_import_status_endpoint,
        name='status'),
    url(r'^species/solve(?P<import_event_id>\d+)/(?P<row_index>\d+)/$',
        solve_endpoint, name='solve'),
    url(r'^update/%s/(?P<row_id>\d+)/$' % _type_pattern,
        update_row_endpoint, name='update_row'),
    url(r'^commit/%s/$' % _import_api_pattern, commit_endpoint, name='commit'),

    url(r'^export/species/all', export_all_species, name='export_all_species'),
    url(r'^export/species/(?P<import_event_id>\d+)$',
        export_single_species_import, name='export_single_species_import'),
    url(r'^export/tree/(?P<import_event_id>\d+)$', export_single_tree_import,
        name='export_single_tree_import'),

    # API
    url(r'^api/merge$', merge_species, name='merge'),
    url(r'^api/counts', counts, name='counts'),
)

if not feature_enabled(None, 'bulk_upload'):
    urlpatterns = patterns('')

opentreemap/opentreemap/urls.py
# -*- coding: utf-8 -*-
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import division

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import RedirectView
from django.contrib import admin

from django_tinsel.decorators import route

from treemap.views import (user_view, root_settings_js_view,
                           profile_to_user_view, user_audits_view,
                           instance_not_available_view, update_user_view,
                           unsupported_view, landing_view, scss_view,
                           upload_user_photo_view, forgot_username_view,
                           instances_geojson_view)
from treemap.instance import URL_NAME_PATTERN
from treemap.urls import USERNAME_PATTERN
from treemap.ecobenefits import within_itree_regions_view

from registration_backend.views import RegistrationView


admin.autodiscover()
instance_pattern = r'^(?P<instance_url_name>' + URL_NAME_PATTERN + r')'


# Testing notes:
# We want to test that every URL succeeds (200) or fails with bad data (404).
# If you add/remove/modify a URL, please update the corresponding test(s).
# For URLs included via <app>.urls, see <app>/tests
# For "top level" URLs defined here, see treemap/tests/urls.py (RootUrlTests)

urlpatterns = patterns(
    '',
    (r'^robots.txt$', RedirectView.as_view(
        url='/static/robots.txt', permanent=True)),
    # Setting permanent=False in case we want to allow customizing favicons
    # per instance in the future
    (r'^favicon\.png$', RedirectView.as_view(
        url='/static/img/favicon.png', permanent=False)),
    url('^comments/', include('django.contrib.comments.urls')),
    url(r'^', include('geocode.urls')),
    url(r'^$', landing_view),
    url(r'^config/settings.js$', root_settings_js_view),
    url(r'^users/%s/$' % USERNAME_PATTERN,
        route(GET=user_view, PUT=update_user_view), name='user'),
    url(r'^users/%s/edits/$' % USERNAME_PATTERN,
        user_audits_view, name='user_audits'),
    url(r'^users/%s/photo/$' % USERNAME_PATTERN,
        upload_user_photo_view, name='user_photo'),
    url(r'^api/v(?P<version>\d+)/', include('api.urls')),
    # The profile view is handled specially by redirecting to
    # the page of the currently logged in user
    url(r'^accounts/profile/$', profile_to_user_view, name='profile'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'}),
    url(r'^accounts/forgot-username/$', forgot_username_view,
        name='forgot_username'),
    url(r'^accounts/', include('registration_backend.urls')),
    # Create a redirect view for setting the session language preference
    # https://docs.djangoproject.com/en/1.0/topics/i18n/#the-set-language-redirect-view  # NOQA
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^not-available$', instance_not_available_view,
        name='instance_not_available'),
    url(r'^unsupported$', unsupported_view, name='unsupported'),
    url(r'^main\.css$', scss_view, name='scss'),
    url(r'^eco/benefit/within_itree_regions/$', within_itree_regions_view,
        name='within_itree_regions'),
    url(r'^instances/$', instances_geojson_view),
    url(instance_pattern + r'/accounts/register/$',
        RegistrationView.as_view(),
       name='instance_registration_register'),
    url(instance_pattern + r'/', include('treemap.urls')),
    url(instance_pattern + r'/importer/', include('importer.urls',
                                                  namespace='importer')),
    url(instance_pattern + r'/export/', include('exporter.urls')),
    url(instance_pattern + r'/comments/', include('otm_comments.urls')),
)

if settings.USE_JS_I18N:
    js_i18n_info_dict = {
        'domain': 'djangojs',
        'packages': settings.I18N_APPS,
    }

    urlpatterns = patterns('', url(r'^jsi18n/$',
                           'django.views.i18n.javascript_catalog',
                           js_i18n_info_dict)) + urlpatterns

if settings.EXTRA_URLS:
    for (url_pattern, url_module) in settings.EXTRA_URLS:
        urlpatterns = patterns('', url(url_pattern,
                                       include(url_module))) + urlpatterns

if settings.DEBUG:
    urlpatterns = patterns(
        '', url(r'^admin/', include(admin.site.urls))) + urlpatterns

handler404 = 'treemap.views.error_404_view'
handler500 = 'treemap.views.error_500_view'
# Not hooked up yet
handler503 = 'treemap.views.error_503_view'

opentreemap/importer/templates/importer/partials/clientside_templates.html
<script type="text/template" id="error-template">
  <div class="error-popup popover fade bottom in" style="margin: 0; display: block; width: 200px;">
    <div class="arrow"></div>
    <h3 class="popover-title"><%= header %></h3>
    <div class="popover-content">
      <%= content %>
    </div>
  </div>
</script>

<script type="text/template" id="species-error-content">
  <div>
    <div>That species couldn't be found in the database.</div>
    <div>Did you mean: <%= possible %>?</div>
    <div>
      <a class="yes btn btn-success btn-small">Yes</a>
      <a class="moreoptions btn btn-info btn-small">More Options</a>
      <a class="cancel btn btn-danger btn-small">Cancel</a>
    </div>
  </div>
</script>

<script type="text/template" id="generic-error">
  <div>
    <input type="text" value="<%= value %>" name="<%= field %>">
    <a class="update btn btn-info btn-small">Update</a>
    <a class="cancel btn btn-alert btn-small">Cancel</a>
  </div>
</script>

<script type="text/template" id="species-error-more-content">
  <div>Find a species by name:</div>
  <div><input class="speciesbyname"></div>
  <div>Or select from a list:</div>
  <div>
    <select class="specieslist">
      <% _.each(species, function(s,i) { %>
      <option data-index="<%= i %>"><%= s %></option>
      <% }); %>
    </select>
  </div>
  <div>
    <a class="select btn btn-success btn-small">Select</a>
    <a class="cancel btn btn-alert btn-small">Cancel</a>
  </div>
</script>

<script type="text/template" id="merge-template">
  <h1>Merge Species</h1>
  <div class="mergespecies">
    <table data-row="<%= fields.rowidx %>"
           class="table table-condensed table-striped">
      <tr>
        <th>Field</th>
        <% _.each(fields.header, function(f) { %><th><%= f %></th><% }) %>
      </tr>
      <% _.each(field_order, function(fo) {
         var f = fields.indexed_data[fo]; %>
      <tr data-field="<%= f.field %>">
        <td>
          <%= f.field %></td>
        <% _.each(f.data, function(d) { %>
        <td>
          <% if (f.needsMerge) { %><input type="checkbox"><% } %>
          <%= d %>
        </td>
        <% }); %>
      </tr>
      <% }) %>
      <tr><td></td>
        <td><button data-matches="new">Create New Species</button></td>
      <% _.each(fields.keys, function(k) { %>
        <td><button data-matches="<%= k %>">Merge Species</button></td>
      <% }); %>
    </table>
  </div>
</script>

<script type="text/template" id="pager-template">
  <div class="pages pagination pagination-small">
    <ul>
      <li><a href="#">&lt;</a></li>
      <li><a href="#">&lt;&lt;</a></li>
      <% _.each(_.range(start_page, end_page), function(i) { %>
        <li
          <% if (i == page) { %> class="active" <% } %>
          ><a href="#"><%= i + 1 %></a>
        </li>
      <% }); %>
      <li><a href="#">&gt;&gt;</a></li>
      <li><a href="#">&gt;</a></li>
    </ul>
  </div>
</script>

opentreemap/importer/templates/importer/partials/file_status.html
{% extends "importer/partials/status.html" %}
{% load i18n %}

{% block main %}
<div class="col-md-12">
  <div class="well">
    <h4>There were errors in the file structure: </h4>
    {% with errors=ie.errors_as_array %}
      {% if errors %}
        <ul class="no-bullet">
          {% for error in errors %}
            {% if error.data %}
              <li>{{ error.msg }}:
                <ul>
                  {% for item in error.data %}
                    {% if item %}
                      <li><b>{{ item }}</b></li>
                    {% endif %}
                  {% endfor %}
                </ul>
              </li>
            {% else %}
              <li>{{ error.msg }}</li>
            {% endif %}
          {% endfor %}
        </ul>
      {% endif %}
      {% if is_missing_field %}
        <div>
          {% trans "The CSV must contain all of the following columns:" %}
          <ul>
          {% for field in required_fields %}
            <li>{{ field }}</li>
          {% endfor %}
          </ul>
        </div>
      {% endif %}
      {% if has_unmatched_field %}
        <div>
          {% trans "The CSV may contain only the following columns:" %}
          <ul>
          {% for field in legal_fields %}
            <li>{{ field }}</li>
          {% endfor %}
          </ul>
        </div>
      {% endif %}
    {% endwith %}
  </div>
</div>
{% endblock main %}

opentreemap/importer/templates/importer/partials/import_table.html
<table class="table table-hover">
    <thead>
        <tr>
            <th>Import Event</th>
            <th>Status</th>
            <th>Rows</th>
            <th>View</th>
        </tr>
    </thead>
    <tbody>
    {% for ie in things %}
        <tr>
            <td>{{ ie }}</td>
            <td>{{ ie.status_summary }}</td>
            <td>
                {% if ie.is_finished %}
                    {{ ie.row_count }}
                {% elif ie.is_loading %}
                    {{ ie.row_count }}
                {% elif ie.is_running %}
                    {{ ie.completed_row_count }} / {{ ie.row_count }}
                {% endif %}
            </td>
            <td>
                <a href="{% url 'importer:status' import_type=import_type import_event_id=ie.pk instance_url_name=request.instance.url_name %}">View</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

opentreemap/importer/templates/importer/partials/import_tables.html
<div id="import-tables">
  <div class="row">
    <div class="col-md-12">
      <img src="/static/img/spinner.gif" class="spinner pull-right" style="display:none;">
      <h2>Imports</h2>
      <hr>

      <h4>Active Tree Imports</h4>
      {% include 'importer/partials/import_table.html' with things=active_trees import_type="tree" %}
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-12">
      <h4>Finished Tree Imports</h4>
      {% include 'importer/partials/import_table.html' with things=finished_trees import_type="tree" %}
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-12">
      <h4>Active Species Imports</h4>
      {% include 'importer/partials/import_table.html' with things=active_species import_type="species" %}
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-12">
      <h4>Finished Species Imports</h4>
      {% include 'importer/partials/import_table.html' with things=finished_species import_type="species" %}
    </div>
  </div>

  <input type="hidden" name="imports-finished" value="{{ imports_finished }}">
</div>

opentreemap/importer/templates/importer/partials/imports.html
{% load i18n %}

<div class="contained topper">
  <div>
    <div class="col-md-12">
      <div>
        <div>
          <div class="row">
            <div class="col-md-6">
              <div class="well">
                <form id="import-trees-form">
                  {% csrf_token %}
                  <button class="btn btn-info pull-right" type="submit" disabled>Import</button>
                  <h4>Tree Import</h4>
                  <input type="hidden" name="type" value="tree">
                  <div class="input-group">
                    File to Upload: <input type="file" name="file">
                  </div><!-- /input-group -->
                  <div id="importer-tree-units" style="display: none;">
                    {% with u=importer_instance_units %}
                    {% with pl=u.plot_length pw=u.plot_width td=u.tree_diameter th=u.tree_height tch=u.tree_canopy_height %}
                    {% blocktrans %}
                    <h5>Unit Warning</h5>
                    <p>The following units are used for your tree map.</p>
                    <p>Please ensure that your file contains measurements of the same unit.</p>
                    <p>Plot Length: {{ pl }}</p>
                    <p>Plot Width: {{ pw }}</p>
                    <p>Tree Diameter: {{ td }}</p>
                    <p>Tree Height: {{ th }}</p>
                    <p>Tree Canopy Height: {{ tch }}</p>
                    {% endblocktrans %}
                    {% endwith %}
                    {% endwith %}
                  </div>
                </form>
              </div>
            </div>
            <div class="col-md-6">
              <div class="well">
                <form id="import-species-form">
                  {% csrf_token %}
                  <button class="btn btn-info pull-right" type="submit" disabled>Import</button>
                  <h4>Species Import</h4>
                  <input type="hidden" name="type" value="species">
                  <div class="input-group">
                    File to Upload: <input type="file" name="file">
                  </div><!-- /input-group -->
                </form>
              </div>
            </div>
          </div>

          {% include 'importer/partials/import_tables.html' %}

<!-- TODO: Uncomment when species exporting is completed -->
<!--           <div class="row"> -->
<!--             <div class="col&#45;md&#45;12"> -->
<!--               <h2 class="top&#45;pad&#45;lg">Export</h2> -->
<!--               <hr> -->
<!--               <a href="{% url 'importer:export_all_species' instance_url_name=request.instance.url_name %}" class="btn btn&#45;info"> -->
<!--                 Export All Species -->
<!--                 <i class="icon&#45;forward"></i> -->
<!--               </a> -->
<!--             </div> -->
<!--           </div> -->

        </div>
      </div>
    </div>
  </div>
</div> <!-- END CONTAINER -->

opentreemap/importer/templates/importer/partials/merge_species.html
{% load l10n %}

<tr class='js-merge-controls' style="display: none;">
    <td colspan="{{ panel.field_names|length }}">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th>Field</th>
                  {% for column in row.columns_for_merge %}
                    <th>{{ column.title }}</th>
                  {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for field in row.fields_to_merge %}
                    <tr class="danger">
                        <td>{{ field.name }}</td>
                      {% for value in field.values %}
                        <td>
                            <input type="radio"
                                   id="{{ value.id }}"
                                   name="{{ field.id }}"
                                   value="{{ value.value }}"
                                   {% if value.checked %}checked{% endif %}>
                            <label for="{{ value.id }}">{{ value.value }}</label>
                        </td>
                      {% endfor %}
                    </tr>
                {% endfor %}
                <tr>
                    <td>
                      <button class="btn btn-sm js-hide">Hide</button>
                    </td>
                  {% for column in row.columns_for_merge %}
                    <td>
                      {% if column.species_id %}
                        <button class="btn btn-sm js-merge"
                                data-merge-field-names="{{ row.merge_field_names }}"
                                data-radio-group-names="{{ row.radio_group_names }}"
                                data-href="{% url 'importer:solve' instance_url_name=request.instance.url_name import_event_id=panel.import_event_id row_index=row.index %}?species={{ column.species_id|unlocalize }}">
                          {{ column.action_title }}
                        </button>
                      {% endif %}
                    </td>
                  {% endfor %}
                </tr>
            </tbody>
        </table>
    </td>
</tr>

opentreemap/importer/templates/importer/partials/resolve_popover.html
{% extends "treemap/partials/popover.html" %}
{% load l10n %}

{% block title %}Field Error{% endblock title %}

{% block content_text %}
<p>There was an error with this field:</p>
<ul><li><b>{{ field.msg }}</b></li></ul>
<p>Please provide a new value:</p>
{% endblock content_text %}

{% block extra_content_input_attributes %}
value="{{ field.value }}"
{% endblock extra_content_input_attributes %}
<br>
{% block extra_save_classes %}resolver-popover-accept{% endblock extra_save_classes %}

{% block extra_save_attributes %}
data-url="{% url 'importer:update_row' instance_url_name=request.instance.url_name import_type=panel.import_type row_id=field.row_id %}"
data-field-name="{{ field.name }}"
{% endblock extra_save_attributes %}

opentreemap/importer/templates/importer/partials/row_status.html
{% extends "importer/partials/status.html" %}
{% load i18n %}

{% block main %}
<div class="col-md-12">
    <ul class="nav nav-tabs">
    {% for panel in panels %}
      <li{% if panel.name == active_panel_name %} class="active"{% endif %}>
        <a href="#import-panel-{{ panel.name }}" data-toggle="tab">
          {{ panel.title }} ({{ panel.row_count }})
        </a>
      </li>
    {% endfor %}
    </ul>

    <div class="tab-content">
    {% for panel in panels %}
      <div class="tab-pane {% if panel.name == active_panel_name %}active{% endif %}"
          id="import-panel-{{ panel.name }}">
        {% include "importer/partials/status_table.html" %}
      </div>
    {% endfor %}
    </div>
</div>
{% endblock main %}

{% block extra_buttons %}
    {% if ie.is_finished %}
        <a data-action="commit" class="btn btn-info btn-large" href="{{ commit_url }}">
          <i class="icon-plus-circled"></i>
          {% trans "Add to Tree Map" %}
        </a>
    {% endif %}
{% endblock extra_buttons %}

opentreemap/importer/templates/importer/partials/species_resolve_popover.html
{% extends "treemap/partials/popover.html" %}
{% load l10n %}

{% block title %}Species Field Error{% endblock title %}

{% block content %}
<p>{{ field.msg }}</p>
<p>Did you mean: "{{ field.custom_resolver.suggestion.display_name }}"?</p>
<input type="hidden"
       data-typeahead-hidden="true"
       class="species-resolver-typeahead-hidden popover-correction"
       value="{{ field.custom_resolver.suggestion.pk|unlocalize }}"/>
<input class="popover-correction species-resolver-typeahead"
       data-typeahead-url="{% url 'species_list_view' instance_url_name=request.instance.url_name %}"
       value="{{ field.custom_resolver.suggestion.display_name }}"/>
{% endblock content %}

{% block extra_save_classes %}resolver-popover-accept{% endblock extra_save_classes %}

{% block extra_save_attributes %}
data-url="{% url 'importer:update_row' instance_url_name=request.instance.url_name import_type=panel.import_type row_id=field.row_id %}"
data-field-name="species"
{% endblock extra_save_attributes %}

opentreemap/importer/templates/importer/partials/status.html
{% load i18n %}

<div class="contained topper">
  <div>
    <div class="col-md-12">
      <div>
        <div>
          <div class="row">
            <div class="col-md-12">
              <h2>{% trans "Import Status" %}</h2>
              <hr>
            </div>
          </div>
          <br>
          <div class="row">
            {% block main %}
            {% endblock main %}
          </div>

          {% block extra_buttons %}
          {% endblock extra_buttons %}

          <a class="btn btn-info btn-large pull-left" data-action="back"
              href="{% url 'importer:list_imports' instance_url_name=request.instance.url_name %}">
              <i class="icon-left-open"></i>
            {% trans "Back to Uploads" %}
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

opentreemap/importer/templates/importer/partials/status_table.html
{% load i18n %}

<div  class="tab-contents">
     <table class="table{% if panel.name == 'merge_required' %} table-hover{% endif %}">
        <thead>
            <tr>
                {% for name in panel.field_names %}
                    <th>{{ name }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% if panel.rows %}
                {% for row in panel.rows %}
                    <tr class="js-import-row">
                        {% for field in row.fields %}
                            {% if field.show_resolver %}
                                {% if field.custom_resolver.is_species %}
                                    {% include "importer/partials/species_resolve_popover.html" %}
                                {% else %}
                                    {% include "importer/partials/resolve_popover.html" %}
                                {% endif %}
                            {% else %}
                                <td class="{{ field.css_class }}" data-field-name="{{ field.name }}">{{ field.value }}</td>
                            {% endif %}
                        {% endfor %}
                    </tr>
                    {% if panel.name == 'merge_required' %}
                        {% include 'importer/partials/merge_species.html' %}
                    {% endif %}
                {% endfor %}
            {% else %}
                <tr>
                    <td class="no-rows" colspan="{{ panel.field_names|length }}">
                        {% trans 'No rows' %}
                    </td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

{% include 'treemap/partials/paging_controls.html' with paging=panel.rows url=panel.paging_url %}